FROM python:3.9
COPY ./webhook ./

RUN pip install --no-cache-dir --upgrade -r /requirements.txt
RUN pip install uvicorn
RUN pip install apscheduler

EXPOSE 8081
CMD ["python", "-m", "uvicorn", "main:app", "--reload", "--host", "0.0.0.0", "--port", "8081"]
