apiVersion: apps/v1
kind: Deployment
metadata:
 name: tech-challenge-deployment
spec:
 replicas: 2
 selector:
    matchLabels:
      app: tech-challenge
 template:
    metadata:
      labels:
        app: tech-challenge
    spec:
      containers:
      - name: tech-challenge
        # image: tech_challenge-app/tech-challenge:latest
        image: guilhermegomes1/tech_challenge-app
        ports:
        - containerPort: 8080
